# Generated by Django 3.2.13 on 2022-10-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='profile',
            new_name='article',
        ),
    ]
