# Generated by Django 3.2.13 on 2022-10-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
