# Generated by Django 3.2.13 on 2022-10-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie_name',
            field=models.CharField(max_length=30),
        ),
    ]
